export { InitialPage } from './InitialPage/InitialPage';
export { CatalogPage } from './CatalogPage/CatalogPage';
export { ReleasePage } from './ReleasePage/ReleasePage';
export { SchedulePage } from './SchedulePage/SchedulePage';
export { TeamPage } from './TeamPage/TeamPage';
export { ManageTitlesPage } from './ManageTitlesPage/ManageTitlesPage';
export { LoginPage } from './LoginPage/LoginPage';
export { RegistrationPage } from './RegistrationPage/RegistrationPage';
export { ErrorPage } from './ErrorPage/ErrorPage';
