export { InitialPage } from './InitialPage/InitialPage';
export { CatalogPage } from './CatalogPage/CatalogPage';
export { ReleasePage } from './ReleasePage/ReleasePage';
export { SchedulePage } from './SchedulePage/SchedulePage';
export { TeamPage } from './TeamPage/TeamPage';
export { SettingsPage } from './SettingsPage/SettingsPage';
export { AuthPage } from './AuthPage/AuthPage';
export { ErrorPage } from './ErrorPage/ErrorPage';
export { TermsPage } from './TermsPage/TermsPage';
