export { Initial } from './Initial/Initial'
export { Catalog } from './Catalog/Catalog'
// export { Schedule } from './Schedule/Schedule'
// export { Team } from './Team/Team'
// export { Donate } from './Donate/Donate'
// export { Rules } from './Rules/Rules'
// export { Profile } from './Profile/Profile'
// export { Login } from './Login/Login'
// export { Favorites } from './Favorites/Favorites'
// export { Page404 } from './Page404/Page404'
// export { Release } from './Release/Release'
